### PR TITLE
Market Features New Look(ish) and Feel

### PR DESCRIPTION
**Pull request by Havanero**
Made a few changes to click straight into the failure from the summary table, also added a red cell on failure table.

Added 
exception reporting if any at the end of the report link from summary table
market_feauture-0 1 1

### CODE REVIEW

**Comment by nusco** [comment]
Looks good! @StefanRatzke, can you merge?

**Comment by nusco** [comment]
@StefanRatzke, this is your first real pull request. You're a project maintainer now ;)

**Comment by StefanRatzke** [comment]
Yes I think it is Caleb wie told me that he Wanst to add the error Message. How are Young ?

Von meinem iPad gesendet

**Comment by StefanRatzke** [comment]
Great thanks have a nice das

Von meinem iPad gesendet

**Comment by Havanero** [comment]
Let me know if you want to review the changes or merge them accordingly.

**Comment by nusco** [comment]
Yo, Stefan. I'm fine. :) I'm working hard in Berlin. Challenging job, which
is something I really needed.

How are things in Frankfurt? Any news in the team? Still delivering
reliably?


   Paolo "Nusco" Perrotta, Italy

**Comment by StefanRatzke** [comment]
Well I'm fine, i hope the team will deliver reliably, but I'm
currently on holiday for 2 weeks. 

	A lot of work at home to do 

	gruß 

	Stefan 

	-----Original-Nachricht----- 

	Betreff: Re: [market-features] Market Features New Look(ish) and Feel
(#2) 

	Datum: Tue, 06 Oct 2015 23:19:43 +0200 

	Von: nusco <notifications@github.com> 

	An: StefanRatzke/market-features <market-features@noreply.github.com>


	  Yo, Stefan. I'm fine. :) I'm working hard in Berlin. Challenging
job, which
 is something I really needed.

 How are things in Frankfurt? Any news in the team? Still delivering
 reliably?

 Paolo "Nusco" Perrotta, Italy

 On Tue, Oct 6, 2015 at 8:14 PM, StefanRatzke
<notifications@github.com>
 wrote:

 > Yes I think it is Caleb wie told me that he Wanst to add the error
 > Message. How are Young ?
 >
 > Von meinem iPad gesendet
 >
 > > Am 06.10.2015 um 14:35 schrieb nusco <notifications@github.com>:
 > >
 > > @StefanRatzke, this is your first real pull request. You're a
project
 > maintainer now ;)
 >
 > >
 > > —
 > > Reply to this email directly or view it on GitHub.
 > >
 >
 > —
 > Reply to this email directly or view it on GitHub
 >
<https://github.com/StefanRatzke/market-features/pull/2#issuecomment-145951438>
 > .
 >

	—
Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/StefanRatzke/market-features/pull/2#issuecomment-146005181

**Comment by nusco** [comment]
oh, I can imagine :)


   Paolo "Nusco" Perrotta, Italy

**Comment by Havanero** [comment]
I've been playing around with Jenkins plugin API and thought about display the results of the above summary inside the project and build job in the actual jenkins page.... Let me know your thoughts!

image

**Comment by Havanero** [comment]
View from project page: )
image

**Comment by nusco** [comment]
This is awesome. It fixes the main problem we had with this: most people in
the company are not proactive in searching for information, so the summary
page gets ignored. Now it's right in their face :)

Thank you, Caleb!

    Paolo "Nusco" Perrotta, Italy

**Comment by StefanRatzke** [comment]
Moin Caleb,
Geräte Job, I like it very much
Gruß 
Stefan


Von meinem iPad gesendet

**Comment by Havanero** [comment]
Thank you Paulo, Thank you Stefan.

I've noticed that too!! people don't like to click on the archived html for some reason. 

I will wait until you guys will be here and maybe i do a brief walk-through. 

Regards,
C.

**Comment by nusco** [comment]
:tada:

**Pull request merged**
