### PR TITLE
hot fix - wrong skip count

### PR DESCRIPTION
**Pull request by Havanero**
I broke skip count...

### CODE REVIEW

**Comment by StefanRatzke** [comment]
Done

**Comment by Havanero** [comment]
Can we have a tag for 10?

**Comment by Havanero** [comment]
Maybe wait a little for the tag, I can see it is not showing ok on windows
:(

**Comment by Havanero** [comment]
OK done... you can now create a tag.

**Comment by StefanRatzke** [comment]
Yes sure tomorrow I will create a new tag an inform you once it is finished

**Comment by Havanero** [comment]
Thanks.

**Comment by StefanRatzke** [comment]
create a new tag/version 0.4

**Comment by Havanero** [comment]
thanks - upload complete - could you also pls do a pip install on our
servers - we need to fix the count of skip.

Regards,
C.

**Pull request merged**
