### PR TITLE
New Major Release Change - IntelliJ like look and feel with skip tests included

### PR DESCRIPTION
**Pull request by Havanero**
screenshot from 2015-11-28 10 21 18

### CODE REVIEW

**Comment by Havanero** [comment]
Changes also includes:  

 - performance timings for each tests
 - date and time of execution
-  collapse/expands tests, market features etc

**Comment by nusco** [comment]
looks awesome
:+1:

**Comment by Havanero** [comment]
Thanks...

**Comment by StefanRatzke** [comment]
Hi Caleb,
Thanks for you changes. I merged your changes, please double check

Gruß
Stefan

**Comment by Havanero** [comment]
Thanks Stefan - I'll check
Regards,
Caleb

**Comment by Havanero** [comment]
Looks good - I can see all my changes on both yours and my fork.

**Pull request merged**
